# Generated by Django 4.2.6 on 2023-10-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_no', models.CharField(max_length=20)),
                ('cost_centre', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20)),
                ('full_description', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('tag_axle', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
                ('towbar', models.BooleanField(default=False)),
            ],
        ),
    ]
