# Generated by Django 4.2.6 on 2023-10-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vital_app', '0002_remove_vehicle_full_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tag_axle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='towbar',
        ),
    ]
